name: dart_gdbc
description: A standard interface specification for accessing graph databases based on Dart language --- 一个基于dart语言访问图数据库的标准接口规范
version: 0.0.1
repository: https://github.com/graph-cn/dart_gdbc

environment:
  sdk: '>=2.19.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
