name: dart_gdbc
description: A standard interface specification for accessing graph databases based on Dart language
version: 0.0.2+1
repository: https://github.com/graph-cn/dart_gdbc

environment:
  sdk: '>=2.19.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
