name: dart_gdbc
description: A standard interface specification for accessing graph databases based on Dart language
version: 0.0.4+1
repository: https://github.com/graph-cn/dart_gdbc

environment:
  sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
